project:
  type: website
website:
  title: "ISSS608-Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: hands-onEx/hands-onEx00/hands-onEx00.html
          - text: "A Layered Grammar of Graphics-ggplot2 methods"
            href: hands-onEx/hands-onEx01/hands-onEx01.html
          - text: "Beyond ggplot2 Fundamentals"
            href: hands-onEx/hands-onEx02/hands-onEx02.html
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: In-Class_Ex1.html
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex1.html
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - icon: "bi bi-File-earmark-person"
        href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
   
    extra_resources:
      - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
editor: visual



