project:
  type: website
website:
  title: "ISSS608-CourseWork"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "The Building Block"
        contents:
          - text: "A Layered Grammar of Graphics: ggplot2 methods"
            href: hands-onEx/hands-onEx01/hands-onEx01.qmd
          - text: "Beyond ggplot2 Fundamentals"
            href: hands-onEx/hands-onEx02/hands-onEx02.qmd
          - text: "Programming Interactive Data Visualisation with R"
            href: hands-onEx/hands-onEx03/hands-onEx03.qmd
          - text: "Programming Animated Statistical Graphics with R"
            href: hands-onEx/hands-onEx03-2/hands-onEx03-2.qmd
      - section: "Visual Analytics" 
        contents:
          - text:  "Visualising Distribution:ridgeline plot & raincloud plot"
            href: hands-onEx/hands-onEx04/hands-onEx04.html
          - text:  "Visual Statistical Analysis"
            href: hands-onEx/hands-onEx04-2/hands-onEx04-2.html
          - text:  "Visualising Uncertainty"
            href: hands-onEx/hands-onEx04-3/hands-onEx04-3.html
          - text:  "Funnel Plots for Fair Comparisons"
            href: hands-onEx/hands-onEx04-4/hands-onEx04-4.html
            
      - section: "Visualising and Analysing Multivariate Data"
        contents:
          - text: "Creating Ternary Plot with R"
            href: hands-onEx/hands-onEx05/hands-onEx05.html
          - text:  "Heatmap for Visualising and Analysing Multivariate Data"
            href: hands-onEx/hands-onEx05-3/hands-onEx05-3.html
            
      - section: "Not So Common Chart"
        contents:
          - text:  "Visual Correlation Analysis"
            href: hands-onEx/hands-onEx05-2/hands-onEx05-2.html
            
        
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: hands-onEx/hands-onEx00/hands-onEx00.html
          - text: "A Layered Grammar of Graphics-ggplot2 methods"
            href: hands-onEx/hands-onEx01/hands-onEx01.html
          - text: "Beyond ggplot2 Fundamentals"
            href: hands-onEx/hands-onEx02/hands-onEx02.html
          - text: "Programming Interactive Data Visualisation with R"
            href: hands-onEx/hands-onEx03/hands-onEx03.html
          - text: "Programming Animated Statistical Graphics with R"
            href: hands-onEx/hands-onEx03-2/hands-onEx03-2.html
          - text: "Visualising Distribution"
            href: hands-onEx/hands-onEx04/hands-onEx04.html
          - text: "Visual Statistical Analysis"
            href: hands-onEx/hands-onEx04-2/hands-onEx04-2.html
          - text:  "Visualising Uncertainty"
            href: hands-onEx/hands-onEx04-3/hands-onEx04-3.html
          - text:  "Funnel Plots for Fair Comparisons"
            href: hands-onEx/hands-onEx04-4/hands-onEx04-4.html
          - text:  "Creating Ternary Plot with R"
            href: hands-onEx/hands-onEx05/hands-onEx05.html
          - text:  "Visual Correlation Analysis"
            href: hands-onEx/hands-onEx05-2/hands-onEx05-2.html
          - text:  "Heatmap for Visualising and Analysing Multivariate Data"
            href: hands-onEx/hands-onEx05-3/hands-onEx05-3.html
            
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: https://public.tableau.com/views/In-class_Ex01_17371864504700/1?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link
          - text: "In-class Exercise 4"
            href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.qmd
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - icon: "bi bi-File-earmark-person"
        href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
   
    extra_resources:
      - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
editor: visual



