project:
  type: website
<<<<<<< HEAD
website:
  title: "ISSS608-Coursework"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: hands-onEx/hands-onEx00.html
          - text: "Hands-on Exercise 0"
            href: hands-onEx/hands-onEx01.html
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: In-Class_Ex1.html
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex1.html
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
=======

website:
  title: "ISSS608- Chen,Peng-Wei"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

>>>>>>> 828e18e16ca38e7e40a06c9a0530274ad8771d3b
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
<<<<<<< HEAD
=======
    toc: true

editor: visual
>>>>>>> 828e18e16ca38e7e40a06c9a0530274ad8771d3b

