project:
  type: website
website:
  title: "ISSS608-Coursework"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "The Building Block"
        contents:
          - text: "A Layered Grammar of Graphics: ggplot2 methods"
            href: hands-onEx/hands-onEx01/hands-onEx01.qmd
          - text: "Beyond ggplot2 Fundamentals"
            href: hands-onEx/hands-onEx02/hands-onEx02.qmd
          - text: "Programming Interactive Data Visualisation with R"
            href: hands-onEx/hands-onEx03/hands-onEx03.qmd
          - text: "Programming Animated Statistical Graphics with R"
            href: hands-onEx/hands-onEx03-2/hands-onEx03-2.qmd
      - section: "Visual Analytics" 
        contents:
          - text:  "Visualising Distribution"
            href: hands-onEx/hands-onEx04/hands-onEx04.html
          - text:  "Visual Statistical Analysis"
            href: hands-onEx/hands-onEx04-2/hands-onEx04-2.html
         
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 0"
            href: hands-onEx/hands-onEx00/hands-onEx00.html
          - text: "A Layered Grammar of Graphics-ggplot2 methods"
            href: hands-onEx/hands-onEx01/hands-onEx01.html
          - text: "Beyond ggplot2 Fundamentals"
            href: hands-onEx/hands-onEx02/hands-onEx02.html
          - text: "Programming Interactive Data Visualisation with R"
            href: hands-onEx/hands-onEx03/hands-onEx03.html
          - text: "Programming Animated Statistical Graphics with R"
            href: hands-onEx/hands-onEx03-2/hands-onEx03-2.html
          - text: "Visualising Distribution"
            href: hands-onEx/hands-onEx04/hands-onEx04.html
          - text: "Visual Statistical Analysis"
            href: hands-onEx/hands-onEx04-2/hands-onEx04-2.html
      - text: "In-class Exercise"
        menu:
          - text: "In-class Exercise 1"
            href: https://public.tableau.com/views/In-class_Ex01_17371864504700/1?:language=en-US&:sid=&:display_count=n&:origin=viz_share_link
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.qmd
    right:
      - icon: "bi bi-house-fill" 
        href: index.qmd
        text: Home
      - icon: "bi bi-File-earmark-person"
        href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
   
    extra_resources:
      - https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css
editor: visual



