---
title: "In Class Exercise 5"
author: "Chen.PengWei"
date-modified: "last-modified"
execute:
  echo: true
  eval: true
  warning: false
  freeze: true
---

# 2.Getting Started

```{r}
pacman::p_load(tidyverse, readxl,SmartEDA, easystats, gtsummary,ggplot2 ,ggstatsplot)
```

```{r}
car_resale <-
  read_xls("data/ToyotaCorolla.xls","data")
```

## 2.1 Different methods of Data overview

::: panel-tabset
## Stat summary

```{r}
summary(car_resale)
```

## Glimpse

```{r}
glimpse((car_resale))
```

## list

```{r}
list(car_resale)
```
:::

::: panel-tabset
## ExpData(type=1)

```{r}
summary1 <- car_resale %>%
  ExpData(type=1)
```

No. of zero variance variables (uniform) = 1:\
There is zero variance in the value of 1 variable. This means that all values ​​of the variable are the same.

## ExpData(type=2)

```{r}
car_resale %>%
  ExpData(type=2)
```
:::

```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears", "Cylinders", "Fuel_Type", "Color", "ABS", "Airbag_1",
          "Met_Color", "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee", "CD_Player", "Airbag_2", "Airco", "Automatic_airco", 
          "Boardcomputer", "Mistlamps", "Central_Lock", "Powered_Windows", "Power_Steering", "Radio",
          "Sport_Model", "Backseat_Divider", "Metallic_Rim", "Radio_cassette", "Tow_Bar")


car_resale <- read_xls("data/ToyotaCorolla.xls", sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%   
  mutate_each_(funs(factor(.)),cols)  

str(car_resale)
    
```

# 3. Add summary Statistics into Metadata output

```{r}
car_resale %>%
  ExpNumViz(target=NULL,
            nlim=10,
            Page=c(2,2))
```

```{r}
car_resale %>%
  ExpCatViz(
    target = NULL,
    col = "sky blue",
    clim = 6,  
    margin = 6,  
    Page = c(2, 2),
    sample = 16
  ) 
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM +
Weight + Guarantee_Period, data =
car_resale)
model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <-check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 +  KM +
Weight + Guarantee_Period, data =
car_resale)
check_normality(model1)
```

```{r}
#|fig-weight = 12
#|fig-height = 18
check_model(model1)
```

```{r}
summary(model1)
```

Organize the summary part into the table

```{r}
tbl_regression(model1,intercept=TRUE)
```

```{r}
tbl_regression(model1,intercept=TRUE) %>%
  add_glance_source_note(label = list(sigma  ~ "\U03C3"), #secret code
include = c(r.squared, adj.r.squared,
AIC, statistic, p.value, sigma))
```

```{r}
p_model1 <- model_parameters(model1)
print(p_model1)
```

```{r}
ggcoefstats(model1,
           output="plot")
```
